#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-anyio
Version  : 3.5.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/4f/d0/b957c0679a9bd0ed334e2e584102f077c3e703f83d099464c3d9569b7c8a/anyio-3.5.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/4f/d0/b957c0679a9bd0ed334e2e584102f077c3e703f83d099464c3d9569b7c8a/anyio-3.5.0.tar.gz
Summary  : High level compatibility layer for multiple asynchronous event loop implementations
Group    : Development/Tools
License  : MIT
Requires: pypi-anyio-license = %{version}-%{release}
Requires: pypi-anyio-python = %{version}-%{release}
Requires: pypi-anyio-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(idna)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(sniffio)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
Unnamed repository; edit this file 'description' to name the repository.

%package license
Summary: license components for the pypi-anyio package.
Group: Default

%description license
license components for the pypi-anyio package.


%package python
Summary: python components for the pypi-anyio package.
Group: Default
Requires: pypi-anyio-python3 = %{version}-%{release}

%description python
python components for the pypi-anyio package.


%package python3
Summary: python3 components for the pypi-anyio package.
Group: Default
Requires: python3-core
Provides: pypi(anyio)
Requires: pypi(idna)
Requires: pypi(sniffio)

%description python3
python3 components for the pypi-anyio package.


%prep
%setup -q -n anyio-3.5.0
cd %{_builddir}/anyio-3.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649716152
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-anyio
cp %{_builddir}/anyio-3.5.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-anyio/097cca9910ea400331f4eed7d585982b04223e36
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-anyio/097cca9910ea400331f4eed7d585982b04223e36

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
